language: python
jobs:
    include:
        # - name: "Python 3.8.0 on Windows" Needs some change in the project
        #   os: windows
        #   language: shell
        #   before_install:
        #     - choco install python --version 3.8.0
        #     - python -m pip install --upgrade pip
        #   env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - name: "Python 3.8.0 on Xenial Linux"
            python: 3.8
        - name: "Python 3.8.0 on macOS"
            os: osx
            osx_image: xcode11.2
            language: shell
            before_install:
                - python3 -m pip install --upgrade pip
            script:
                - python3 insecure -h
                - python3 insecure -e linkedin -q "OWASP"
                - python3 insecure -e show modules
        - name: "Python 3.8 on FreeBSD"
            python: 3.8
            os: freebsd
        - name: "Python 3.9 on Xenial Linux"
            python: 3.9
        - name: "Python 3.9 on FreeBSD"
            python: 3.9
            os: freebsd
install:
 - "pip install -r requirements"
script:
    - python insecure -h
    - python insecure -e show modules
    - python insecure -e linkedin -q "OWASP"